version: '3.7'
services:
    flask:
        build: .
        command: flask run --host=0.0.0.0
        environment:
            - FLASK_APP=/mnt/app.py
            - FLASK_DEBUG=1
        ports: 
            - "5000:5000"
        volumes:
            - ./app.py:/mnt/app.py
